stages:
- name: stage1
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:xcloudiq-default-redis-cluster
      version: 5.0.6
      answers:
        global.busyboxImageTag: 0.1.0
        global.cert: test
        global.enableIDMRedisCluster: "false"
        global.enableMonitoring: "false"
        global.enableMxRelay: "true"
        global.hmVersion: 20.3.4.1
        global.imagePullPolicy: Always
        global.registry: 081731760779.dkr.ecr.us-east-1.amazonaws.com
        global.sslCert: qa
      name: default-redis-cluster
      targetNamespace: k3stest
timeout: 60
notification: {}
